webtalk_init -webtalk_dir D:/Vivado_Program_Files/20170711_ESP8266/ESP8266_Config_2.1.1/ESP8266_Config_2.1.1.sim/sim_1/behav/xsim.dir/tb_WiFi_Receiver_mac_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Aug 16 14:51:51 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2015.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1412921" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f9faa9da-f37e-485d-9b7c-ff9135840b76" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "23ac9a46402e4f77b8f589e0eada4a32" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "46" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3392 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "4" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.12_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "22720_KB" -context "xsim\\usage"
webtalk_transmit -clientid 664075549 -regid "" -xml D:/Vivado_Program_Files/20170711_ESP8266/ESP8266_Config_2.1.1/ESP8266_Config_2.1.1.sim/sim_1/behav/xsim.dir/tb_WiFi_Receiver_mac_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Vivado_Program_Files/20170711_ESP8266/ESP8266_Config_2.1.1/ESP8266_Config_2.1.1.sim/sim_1/behav/xsim.dir/tb_WiFi_Receiver_mac_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Vivado_Program_Files/20170711_ESP8266/ESP8266_Config_2.1.1/ESP8266_Config_2.1.1.sim/sim_1/behav/xsim.dir/tb_WiFi_Receiver_mac_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
