-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\Config_Client\Config_Client.vhd
-- Created: 2017-08-18 11:42:52
-- 
-- Generated by MATLAB 8.6 and HDL Coder 3.7
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0
-- Target subsystem base rate: 0
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        0
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- cmd_start                     ce_out        0
-- model_sel                     ce_out        0
-- data_stream_send_stb          ce_out        0
-- data_stream_send              ce_out        0
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Config_Client
-- Source Path: Config_Client
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Config_Client IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        data_stream_in_ack                :   IN    std_logic;
        rec_cmd_en                        :   IN    std_logic;
        model_cmd                         :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        ce_out                            :   OUT   std_logic;
        cmd_start                         :   OUT   std_logic;
        model_sel                         :   OUT   std_logic_vector(3 DOWNTO 0);  -- ufix4
        data_stream_send_stb              :   OUT   std_logic;
        data_stream_send                  :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
        );
END Config_Client;


ARCHITECTURE rtl OF Config_Client IS

  -- Component Declarations
  COMPONENT Config_Client_mac
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          data_stream_in_ack              :   IN    std_logic;
          rec_cmd_en                      :   IN    std_logic;
          model_cmd                       :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
          cmd_start                       :   OUT   std_logic;
          model_sel                       :   OUT   std_logic_vector(3 DOWNTO 0);  -- ufix4
          data_stream_send_stb            :   OUT   std_logic;
          data_stream_send                :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Config_Client_mac
    USE ENTITY work.Config_Client_mac(rtl);

  -- Signals
  SIGNAL model_sel_tmp                    : std_logic_vector(3 DOWNTO 0);  -- ufix4
  SIGNAL data_stream_send_tmp             : std_logic_vector(7 DOWNTO 0);  -- ufix8

BEGIN
  u_Config_Client_mac : Config_Client_mac
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              data_stream_in_ack => data_stream_in_ack,
              rec_cmd_en => rec_cmd_en,
              model_cmd => model_cmd,  -- ufix4
              cmd_start => cmd_start,
              model_sel => model_sel_tmp,  -- ufix4
              data_stream_send_stb => data_stream_send_stb,
              data_stream_send => data_stream_send_tmp  -- uint8
              );

  ce_out <= clk_enable;

  model_sel <= model_sel_tmp;

  data_stream_send <= data_stream_send_tmp;

END rtl;

