-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\wifi_server\wifi_server_pkg.vhd
-- Created: 2017-10-04 12:01:33
-- 
-- Generated by MATLAB 8.6 and HDL Coder 3.7
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE wifi_server_pkg IS
  TYPE T_state_type_is_wifi_setup_server_mac IS (IN_Tran1_A, IN_Tran1_Enter, IN_Tran1_Enter1, IN_Tran1_T, IN_Tran2_Enter, IN_Tran2_Enter1, IN_Tran3_Enter, IN_Tran3_Enter1, IN_begin_send_data, IN_data_send_over, IN_device_OK, IN_device_config_OK, IN_initial, IN_pre_rec_data, IN_rec_data, IN_send1_finish, IN_send2_finish, IN_send3_finish, IN_send_cmd1, IN_send_cmd2, IN_send_cmd_over, IN_send_data_over, IN_send_word, IN_send_word1, IN_wait1_cnt, IN_wait_cmd, IN_wait_data, IN_wait_port, IN_wait_server_rec_S, IN_wait_server_rec_T);
END wifi_server_pkg;

