-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\Config_Client\Config_Client_pkg.vhd
-- Created: 2017-09-01 13:38:27
-- 
-- Generated by MATLAB 8.6 and HDL Coder 3.7
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE Config_Client_pkg IS
  TYPE T_state_type_is_Config_Client_mac IS (IN_Initial, IN_Tran1_3, IN_Tran1_A, IN_Tran1_C, IN_Tran1_D, IN_Tran1_E, IN_Tran1_Enter, IN_Tran1_Enter_1, IN_Tran1_Equal, IN_Tran1_M, IN_Tran1_O, IN_Tran1_Plus, IN_Tran1_T, IN_Tran1_W, IN_Tran2_A, IN_Tran2_A1, IN_Tran2_C, IN_Tran2_Comma, IN_Tran2_D, IN_Tran2_E, IN_Tran2_Enter, IN_Tran2_Enter_1, IN_Tran2_Equal, IN_Tran2_J, IN_Tran2_N, IN_Tran2_N1, IN_Tran2_O, IN_Tran2_P, IN_Tran2_Plus, IN_Tran2_Quota, IN_Tran2_Quota1, IN_Tran2_Quota2, IN_Tran2_Quota3, IN_Tran2_R, IN_Tran2_T, IN_Tran2_T1, IN_Tran2_U, IN_Tran2_Underline, IN_Tran2_W, IN_Tran_A, IN_Tran_Enter, IN_Tran_Enter_1, IN_Tran_T, IN_device_OK, IN_device_OK1, IN_device_OK2, IN_send_finish, IN_send_finish1, IN_send_finish2, IN_wait_cnt1, IN_wait_cnt2, IN_wait_cnt3);
END Config_Client_pkg;

