-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\ESP8266_Config\ESP8266_Config_pkg.vhd
-- Created: 2017-09-27 10:37:28
-- 
-- Generated by MATLAB 8.6 and HDL Coder 3.7
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE ESP8266_Config_pkg IS
  TYPE T_state_type_is_wifi_setup_client IS (IN_Tran1_Enter, IN_Tran1_Enter_1, IN_Tran2_Enter, IN_Tran2_Enter_1, IN_Tran3_Enter, IN_Tran3_Enter_1, IN_Tran_A, IN_Tran_Enter, IN_Tran_Enter_1, IN_Tran_T, IN_device_OK, IN_device_config_OK, IN_initial, IN_model_reselect, IN_model_sel_rst, IN_pre_rec_data, IN_rec_data, IN_restart, IN_send_cmd1, IN_send_cmd2, IN_send_cmd3, IN_send_cmd4, IN_send_cmd_over, IN_send_cmd_over1, IN_send_data1, IN_send_data2, IN_send_data_over, IN_send_finish, IN_send_finish1, IN_send_finish2, IN_send_finish3, IN_wait_client_rec_C, IN_wait_client_rec_R, IN_wait_cmd, IN_wait_cmd1, IN_wait_cnt1, IN_wait_data, IN_wait_port);
END ESP8266_Config_pkg;

