-- -------------------------------------------------------------
-- 
-- File Name: D:\Vivado_Program_Files\20170711_ESP8266\ESP8266_Config_0.4\ESP8266_Config_0.4.srcs\sources_1\receive_OK\receive_OK.vhd
-- Created: 2017-07-20 16:04:02
-- 
-- Generated by MATLAB 8.6 and HDL Coder 3.7
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0
-- Target subsystem base rate: 0
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        0
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- model_cmd                     ce_out        0
-- rec_cmd_en                    ce_out        0
-- test_data_stream_in_stb       ce_out        0
-- test_data_stream_in           ce_out        0
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: receive_OK
-- Source Path: receive_OK
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY receive_OK IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        data_stream_in_stb                :   IN    std_logic;
        data_stream_in                    :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        ce_out                            :   OUT   std_logic;
        model_cmd                         :   OUT   std_logic_vector(3 DOWNTO 0);  -- ufix4
        rec_cmd_en                        :   OUT   std_logic;
        test_data_stream_in_stb           :   OUT   std_logic;
        test_data_stream_in               :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
        );
END receive_OK;


ARCHITECTURE rtl OF receive_OK IS

  -- Component Declarations
  COMPONENT WiFi_Receiver_mac
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          data_stream_in_stb              :   IN    std_logic;
          data_stream_in                  :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          model_cmd                       :   OUT   std_logic_vector(3 DOWNTO 0);  -- ufix4
          rec_cmd_en                      :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : WiFi_Receiver_mac
    USE ENTITY work.WiFi_Receiver_mac(rtl);

  -- Signals
  SIGNAL model_cmd_tmp                    : std_logic_vector(3 DOWNTO 0);  -- ufix4

BEGIN
  u_WiFi_Receiver_mac : WiFi_Receiver_mac
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              data_stream_in_stb => data_stream_in_stb,
              data_stream_in => data_stream_in,  -- uint8
              model_cmd => model_cmd_tmp,  -- ufix4
              rec_cmd_en => rec_cmd_en
              );

  ce_out <= clk_enable;

  model_cmd <= model_cmd_tmp;

  test_data_stream_in_stb <= data_stream_in_stb;

  test_data_stream_in <= data_stream_in;

END rtl;

