-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\ESP8266_Config\ESP8266_Config.vhd
-- Created: 2017-09-15 14:11:30
-- 
-- Generated by MATLAB 8.6 and HDL Coder 3.7
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0
-- Target subsystem base rate: 0
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        0
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- data_stream_send_stb          ce_out        0
-- data_stream_send              ce_out        0
-- cmd_start                     ce_out        0
-- model_sel                     ce_out        0
-- rec_data_en                   ce_out        0
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: ESP8266_Config
-- Source Path: ESP8266_Config
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY ESP8266_Config IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        data_stream_in_ack                :   IN    std_logic;
        cmd_over                          :   IN    std_logic;
        byte_to_tx                        :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        data_stream_out_stb               :   IN    std_logic;
        data_stream_out                   :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        rec_cmd_en                        :   IN    std_logic;
        model_cmd                         :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        ce_out                            :   OUT   std_logic;
        data_stream_send_stb              :   OUT   std_logic;
        data_stream_send                  :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
        cmd_start                         :   OUT   std_logic;
        model_sel                         :   OUT   std_logic_vector(3 DOWNTO 0);  -- ufix4
        rec_data_en                       :   OUT   std_logic
        );
END ESP8266_Config;


ARCHITECTURE rtl OF ESP8266_Config IS

  -- Component Declarations
  COMPONENT wifi_setup_client
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          data_stream_in_ack              :   IN    std_logic;
          cmd_over                        :   IN    std_logic;
          byte_to_tx                      :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          data_stream_out_stb             :   IN    std_logic;
          data_stream_out                 :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          rec_cmd_en                      :   IN    std_logic;
          model_cmd                       :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
          data_stream_send_stb            :   OUT   std_logic;
          data_stream_send                :   OUT   std_logic_vector(7 DOWNTO 0);  -- uint8
          cmd_start                       :   OUT   std_logic;
          model_sel                       :   OUT   std_logic_vector(3 DOWNTO 0);  -- ufix4
          rec_data_en                     :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : wifi_setup_client
    USE ENTITY work.wifi_setup_client(rtl);

  -- Signals
  SIGNAL data_stream_send_tmp             : std_logic_vector(7 DOWNTO 0);  -- ufix8
  SIGNAL model_sel_tmp                    : std_logic_vector(3 DOWNTO 0);  -- ufix4

BEGIN
  u_wifi_setup_client : wifi_setup_client
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              data_stream_in_ack => data_stream_in_ack,
              cmd_over => cmd_over,
              byte_to_tx => byte_to_tx,  -- uint8
              data_stream_out_stb => data_stream_out_stb,
              data_stream_out => data_stream_out,  -- uint8
              rec_cmd_en => rec_cmd_en,
              model_cmd => model_cmd,  -- ufix4
              data_stream_send_stb => data_stream_send_stb,
              data_stream_send => data_stream_send_tmp,  -- uint8
              cmd_start => cmd_start,
              model_sel => model_sel_tmp,  -- ufix4
              rec_data_en => rec_data_en
              );

  ce_out <= clk_enable;

  data_stream_send <= data_stream_send_tmp;

  model_sel <= model_sel_tmp;

END rtl;

