-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\ESP8266_Config\ESP8266_Config_pkg.vhd
-- Created: 2017-09-13 11:19:52
-- 
-- Generated by MATLAB 8.6 and HDL Coder 3.7
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE ESP8266_Config_pkg IS
  TYPE T_state_type_is_wifi_setup_client IS (IN_Tran1_Enter, IN_Tran1_Enter_1, IN_Tran_A, IN_Tran_Enter, IN_Tran_Enter_1, IN_Tran_T, IN_device_OK, IN_device_config_OK, IN_initial, IN_send_cmd1, IN_send_cmd2, IN_send_cmd_over, IN_send_finish, IN_send_finish1, IN_wait_cmd, IN_wait_cnt1);
END ESP8266_Config_pkg;

